name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          # Força a leitura de mais linguagens e repositórios
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_repositories: yes
          plugin_repositories_batch: 100 # Aumenta o limite de busca

      - name: Commit generated metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics image"
          file_pattern: metrics.svg
