name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          display: classic
          plugin_languages: yes
          plugin_languages_ignored: not-code
          plugin_languages_limit: 6
          plugin_lines: yes

      - name: Commit generated metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics image"
          file_pattern: metrics.svg
