name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          # Configuração avançada para forçar a leitura das linguagens nos seus repositórios públicos
          plugin_languages: yes
          plugin_languages_skipped: "henrique-amorim-silva" # Substitua ou adicione nomes de repositórios se quiser ignorar algo, ou deixe vazio
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15

      - name: Commit generated metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics image"
          file_pattern: metrics.svg
